export const siteConfig = {
  name: "DRM Aix-en-Provence",
  fullName: "Depannage Rideau Metallique Aix-en-Provence",
  brand: "DRM Aix-en-Provence",
  domain: "depannage-rideau-metallique-aix-en-provence.fr",
  url: "https://depannage-rideau-metallique-aix-en-provence.fr",
  phone: "",
  phoneLink: "/contact/",
  phonePublic: false,
  email: "contact@depannage-rideau-metallique-aix-en-provence.fr",
  city: "Aix-en-Provence",
  cityShort: "Aix-en-Provence",
  postalCode: "13100",
  department: "Bouches-du-Rhone",
  departmentCode: "13",
  region: "Provence-Alpes-Cote d'Azur",
  address: "2 Rue Andre Chenier, 13100 Aix-en-Provence",
  geo: {
    latitude: 43.5263,
    longitude: 5.4454,
  },
  openingHours: "24h/24, 7j/7",
  experience: "25+",
  delai: "30",
  rating: "4.9",
  ratingCount: "138",
  interventions: "5000+",
  heroBg: "realisation-rideau-metallique-lame-pleine-commerce.webp",
};

export const services = [
  {
    id: "depannage",
    name: "Depannage",
    slug: "depannage-rideau-metallique",
    description: "Intervention d'urgence 24h/24 sur rideau metallique en panne",
    shortDescription: "Rideau bloque ? Intervention en moins de 30 minutes.",
  },
  {
    id: "installation",
    name: "Installation",
    slug: "installation-rideau-metallique",
    description: "Pose complete de rideaux metalliques neufs pour commerces et industriels",
    shortDescription: "Pose sur-mesure pour commerces, bureaux et entrepots.",
  },
  {
    id: "reparation",
    name: "Reparation",
    slug: "reparation-rideau-metallique",
    description: "Remise en etat de rideaux metalliques endommages",
    shortDescription: "Lames, moteur, axe, serrure : reparation garantie.",
  },
  {
    id: "motorisation",
    name: "Motorisation",
    slug: "motorisation-rideau-metallique",
    description: "Automatisation de rideaux metalliques manuels existants",
    shortDescription: "Passez a l'electrique avec Somfy, Simu ou Nice.",
  },
  {
    id: "deblocage",
    name: "Deblocage",
    slug: "deblocage-rideau-metallique",
    description: "Liberation urgente de rideaux metalliques coinces",
    shortDescription: "Rideau coince ? Liberation rapide sans degradation.",
  },
  {
    id: "entretien",
    name: "Entretien",
    slug: "entretien-rideau-metallique",
    description: "Maintenance preventive et contrats annuels",
    shortDescription: "Evitez les pannes avec un entretien regulier.",
  },
  {
    id: "fabrication",
    name: "Fabrication",
    slug: "fabrication-rideau-metallique",
    description: "Fabrication sur-mesure de rideaux metalliques",
    shortDescription: "Acier, aluminium, inox : fabrication aux dimensions exactes.",
  },
];

export const zones = [
  { name: "Les Milles", slug: "les-milles", postalCode: "13290", distance: "5 km", lat: 43.5045, lng: 5.3743 },
  { name: "Luynes", slug: "luynes", postalCode: "13080", distance: "5 km", lat: 43.4847, lng: 5.4377 },
  { name: "Le Tholonet", slug: "le-tholonet", postalCode: "13100", distance: "5 km", lat: 43.5253, lng: 5.5097 },
  { name: "Puyricard", slug: "puyricard", postalCode: "13540", distance: "7 km", lat: 43.5805, lng: 5.4276 },
  { name: "Eguilles", slug: "eguilles", postalCode: "13510", distance: "9 km", lat: 43.5675, lng: 5.3543 },
  { name: "Venelles", slug: "venelles", postalCode: "13770", distance: "10 km", lat: 43.5817, lng: 5.4789 },
  { name: "Meyreuil", slug: "meyreuil", postalCode: "13590", distance: "10 km", lat: 43.4920, lng: 5.5135 },
  { name: "Bouc-Bel-Air", slug: "bouc-bel-air", postalCode: "13320", distance: "10 km", lat: 43.4527, lng: 5.4101 },
  { name: "Cabries", slug: "cabries", postalCode: "13480", distance: "12 km", lat: 43.4587, lng: 5.3739 },
  { name: "Ventabren", slug: "ventabren", postalCode: "13122", distance: "12 km", lat: 43.5391, lng: 5.3186 },
  { name: "Gardanne", slug: "gardanne", postalCode: "13120", distance: "13 km", lat: 43.4543, lng: 5.4716 },
  { name: "Saint-Marc-Jaumegarde", slug: "saint-marc-jaumegarde", postalCode: "13100", distance: "10 km", lat: 43.5435, lng: 5.5331 },
  { name: "Simiane-Collongue", slug: "simiane-collongue", postalCode: "13109", distance: "13 km", lat: 43.4321, lng: 5.4188 },
  { name: "Mimet", slug: "mimet", postalCode: "13105", distance: "15 km", lat: 43.4189, lng: 5.5036 },
  { name: "Greasque", slug: "greasque", postalCode: "13850", distance: "15 km", lat: 43.4385, lng: 5.5413 },
  { name: "Vauvenargues", slug: "vauvenargues", postalCode: "13126", distance: "16 km", lat: 43.5503, lng: 5.6053 },
  { name: "Fuveau", slug: "fuveau", postalCode: "13710", distance: "16 km", lat: 43.4490, lng: 5.5602 },
  { name: "Saint-Cannat", slug: "saint-cannat", postalCode: "13760", distance: "18 km", lat: 43.6131, lng: 5.2913 },
  { name: "Peynier", slug: "peynier", postalCode: "13790", distance: "18 km", lat: 43.4537, lng: 5.6471 },
  { name: "Trets", slug: "trets", postalCode: "13530", distance: "20 km", lat: 43.4452, lng: 5.6814 },
  { name: "Rognes", slug: "rognes", postalCode: "13840", distance: "22 km", lat: 43.6582, lng: 5.3479 },
  { name: "Lambesc", slug: "lambesc", postalCode: "13410", distance: "25 km", lat: 43.6520, lng: 5.2629 },
];

export const colors = {
  primary: "#2D3F2A",
  primaryHover: "#1F2C1D",
  accent: "#C28840",
  accentLight: "#D9A062",
  accentHover: "#A66E2E",
  lightBg: "#F5F1E6",
  warmBg: "#EFE8D6",
  darkBg: "#1A1F18",
  white: "#FFFFFF",
  textDark: "#181C16",
  textMuted: "#4F5648",
  textLight: "#8A8D7E",
  border: "#D8D2C0",
  starColor: "#F59E0B",
};

export const marques = [
  "Somfy", "Simu", "ACM", "Came", "Nice", "FAAC", "BFT", "Sommer",
];
